---
language: python
python:
  - 3.6

addons:
  apt:
    update: true

install:
  - pip install pipenv
  - pipenv install --deploy && pipenv install --dev --deploy

script:
  - pipenv run black --check --diff .
